### ISSUE TITLE
Running livetests/cbt_api_livetests.php - Creating default object from empty value

### ISSUE THREAD

**Issue by bartonhammond** [crossbrowsertesting/API-Sample-Scripts#1]
```HP Warning:  Creating default object from empty value in /Users/barton/projects/wisnet/automate/scripts/livetest.php on line 142
PHP Stack trace:
PHP   1. {main}() /Users/barton/projects/wisnet/automate/scripts/livetest.php:0
PHP   2. LiveTest->startTest() /Users/barton/projects/wisnet/automate/scripts/livetest.php:184
PHP   3. LiveTest->callApi() /Users/barton/projects/wisnet/automate/scripts/livetest.php:36
```

**Comment by adamtaylor13** [comment]
@bartonhammond Hey thanks for bringing this to our attention! I figured out what was going on, and I think we've fixed it by switching the default $apiResult from Null to a stdClass. 

This didn't seem like it was a fatal error, but rather just a warning. Can you confirm: 1. That your script now works with the update? 2. It was just a warning, and not an actual error?

**Comment by bartonhammond** [comment]
Yes - initializing to $stdClass fixes it.

Thanks!

**Comment by adamtaylor13** [comment]
Fantastic. Glad to hear it!
